### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ensag-dev** [apertium/apertium-oci-fra#12]
Hello!
Many thanks for the work recently done.
Would be possible to release a new version? So it's included in other places like Debian repository.

**Comment by TinoDidriksen** [comment]
That is being worked on. https://github.com/apertium/organisation/issues/32

**Comment by hectoralos** [comment]
Yes, a new version is scheduled at the end of October. The new version will include the translation on both sides (not only from French) and will cover also Gascon Occitan besides Languedoc Occitan.

**Comment by ensag-dev** [comment]
Oh I didn't know! I'm looking forward then!
